version: "3.9"
volumes:
    database-data:
    code:

services: 
    database:
        image: mariadb:latest
        container_name: maria_db
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_PASSWORD=app
        volumes:
            - database-data:/var/lib/mysql
    webserver:
        build: app
        ports:
          - 80:80
        volumes:
          - code:/var/www/html
        container_name: apache2
          # problem with: - code:/var/www/html linux != windows --> server gets slow --> windows format to linux format
          # solution: get evrything from any ftp server
    codeserver: 
        image: ghcr.io/linuxserver/openssh-server 
        environment:
            - PASSWORD_ACCESS=true # usually needs a privat and public key
            - USER_PASSWORD=ssh
            - USER_NAME=ssh
            - PUID=1000 # any group
            - PGID=33 # group for webserver
        ports:
          - 22:2222
        volumes:
            - code:/var/www/html
        container_name: openssh