= Docker


== Docker-Container

* wesentlich kleinere "vm"
** minimum 

* Kann über 
** 

== Docker-Compose
* Startet die einzenen services 

* STEPS:
** Version definieren:
*** `version: "3.9"`

** Services definieren:
*** `services:`

** Services-namen definieren:
*** `mysql-database:`

** *Image*: von wo holt dich der container die sachen:
*** `image: mariabdb:latest`

** Container-name definieren:
*** `container_name: mariadb`

** Ports freigeben:
*** left pc-port
*** right docker-port
*** `ports: -3306:3006`

** Umgebungsvariablen definieren:
*** BSPW: Password & Benutzername
*** `enviroment: -password: ...`

** Vloume definieren definieren:
*** Was wird vom pc auf den Docker-Container kopiert
*** volume definieren oder direkt angeben
*** siehe code-block

* Docker-Compose file starten:
** `docker-compose up`
** als daemon `docker-compose up -d`

* Komplettes compose-file: 

[source, yml]
----
version: "3.9"
volumes:
    database-data:
services: 
    database:
        image: mariadb:latest
        container_name: maria_db
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_PASSWORD=app
        volumes:
            - database-data:/var/lib/mysql
----

* Webserver definieren:

** Neuen service erstelen
** Dockerfile im php ordner erstellen um Prozess zu verienfachen
*** `/sensorify/Dockerfile`
** Build definieren
*** `build: sensorify`
** Im DOCKERFILE arbeiten
*** PHP-Configuration unter : https://hub.docker.com/_/php'
** PHP-GD LIBRAR

[source, yml]
----

RUN apt-get install -y \
libfreetype6-dev \
libjpeg62-turbo-dev \
libpng-dev libzip-dev

----


[source, yml]
----
version: "3.9"
volumes:
    database-data:
    code:

services: 
    database:
        image: mariadb:latest
        container_name: maria_db
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
            - MYSQL_ROOT_PASSWORD=app
        volumes:
            - database-data:/var/lib/mysql
    webserver:
        build: sensorify
        ports:
          - 80:80
        volumes:
          - code:/var/www/html
----



== dd


== dd
